language: java

jdk: openjdk8

services:
  - docker

install: true

cache:
  directories:
  - $HOME/.m2

script:
  mvn clean install -DcloudName=${cloudName} -DsecurityToken=${securityToken} -Dreportium-job-name=${TRAVIS_JOB_NAME} -Dreportium-job-number=${TRAVIS_JOB_NUMBER} -Dreportium-job-branch=${TRAVIS_BRANCH} -Dreportium-tags="test"
  echo "Perfecto Suite Report- https://${cloudName}.reporting.perfectomobile.com/library?jobName[0]=${TRAVIS_JOB_NAME}&jobNumber[0]=${TRAVIS_JOB_NUMBER}"
